name: Notify about new issue or discussion

on:
  issues:
    types: [opened]
  discussion:
    types: [created]
jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - uses: nmshd/github-notify-action@v1
        with:
          webhook_url: ${{ secrets.MS_TEAMS_WEBHOOK_CONTRIBUTION }}
